project:
  type: website
  output-dir: docs

website:
  title: "Eigenbeam"
  description: "Explorations in Computational Physics"
  navbar:
    background: "#34495e"
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
  page-footer:
    center: "Â© 2026 Eigenbeam"

format:
  html:
    theme:
      light: custom.scss
    toc: true
    toc-depth: 2
    toc-location: right
    code-fold: false
    code-tools: false
    highlight-style: github
    fontsize: 18px
    linestretch: 1.6
    mainfont: "Source Serif 4"
    monofont: "JetBrains Mono"

execute:
  freeze: auto
